/: "HomeController::index"
/projects/commercial: "HomeController::index"
/projects/my: "HomeController::myProjects"
/logger: "LoggerController::index"
/addlog: "LoggerController::addLog"
/admin: "AdminController::index"
/admin/projects: "AdminController::projects"
/admin/add/tags: "AdminController::addTag"
/admin/projects/add: "AdminController::addProject"
/admin/projects/update: "AdminController::saveProject"
/admin/projects/edit : "AdminController::editProject"
/admin/projects/delete: "AdminController::deleteProject"
/login: "AuthController::index"
/try_login: "AuthController::login"
/logout: "AuthController::logout"
/apply_filters: "HomeController::applyFilter"
/get_card_info: "HomeController::getCardInfo"